# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steph's Bubble
description: > # this means to ignore newlines until "baseurl:"
  I'm a Senior Principal Software Engineer in DevSecOps working to improve the Software Development Lifecycle across over 100 teams. I live with my Scotty in the UK working on my crafts (I knit and crochet), reading, listening to music and doing jigsaws and lego.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stephegn.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:slug
