# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steph's Bubble
description: > # this means to ignore newlines until "baseurl:"
  I'm a Software Engineer working at The BBC.
  I graduated from The University of Manchester with a Bsc in Computer Science WIE.
  I am currently working with Java but have worked with PHP and Wordpress for 3 years
  and have spoken at a WordCamp in Manchester.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stephegn.github.io" # the base hostname & protocol for your site
twitter_username: stephegn
github_username:  stephegn

# Build settings
markdown: kramdown
permalink: /:slug
